GET http://localhost:8000/players/63fef2ee757bd7d3c9939688

###

GET http://localhost:8000/players
Content-Type: application/json

{
  "cookies": {
    "name": "express"
  }
}

###

POST http://localhost:8000/players
Content-Type: application/json

{
  "name": "express",
  "highscores": [{
    "songName": "Tempestissimo",
    "score": 9923728,
    "grade": "EX"
  },
  {
    "songName": "Oshama Scramble!",
    "score": 9626531,
    "grade": "AA"
  },
  {
    "songName": "World Vanquisher",
    "score": 9392720,
    "grade": "A"
  }]
}